___
# **Preparación y limpieza de datos**
___


En esta sección se describe el proceso de carga, exploración, filtrado y transformación del dataset utilizado en el análisis.

El objetivo es preparar un conjunto de datos consistente y adecuado para la construcción de visualizaciones que permitan analizar el riesgo hídrico en las provincias del Ecuador, y compararlo de manera global.

El dataset se obtuvo de: [Aqueduct 4.0 Current and Future Global Maps Data](https://www.wri.org/data/aqueduct-global-maps-40-data#download-form)

## **Carga de dataset**

In [1]:
import pandas as pd

> Se cargo el dataset a un release de Github para poder leerlo desde una URL publica

In [2]:
url = "https://github.com/wolfzbp/Global-Water-Indicators-based-on-Aqueduct-4.0/releases/download/v1.0/Aqueduct40_baseline_annual_y2023m07d05.csv"
df = pd.read_csv(url)
df

,string_id,aq30_id,pfaf_id,gid_1,aqid,gid_0,name_0,name_1,area_km2,bws_raw,...,w_awr_tex_qal_label,w_awr_tex_rrr_raw,w_awr_tex_rrr_score,w_awr_tex_rrr_cat,w_awr_tex_rrr_label,w_awr_tex_tot_raw,w_awr_tex_tot_score,w_awr_tex_tot_cat,w_awr_tex_tot_label,w_awr_tex_tot_weight_fraction
0,111011-EGY.11_1-3365,0,111011,EGY.11_1,3365,EGY,Egypt,Al Qahirah,4.223754,9999.0,...,Low - Medium (1-2),1.622678,2.163858,2.0,Medium - High (2-3),2.509062,3.705279,3.0,High (3-4),0.877551
1,111011-EGY.15_1-3365,1,111011,EGY.15_1,3365,EGY,Egypt,As Suways,1846.012343,9999.0,...,Low - Medium (1-2),1.622678,2.163858,2.0,Medium - High (2-3),2.509062,3.705279,3.0,High (3-4),0.877551
2,111011-EGY.15_1-None,2,111011,EGY.15_1,-9999,EGY,Egypt,As Suways,30.526067,9999.0,...,Low - Medium (1-2),1.622678,2.163858,2.0,Medium - High (2-3),2.509062,3.705279,3.0,High (3-4),0.877551
3,111011-None-3365,3,111011,-9999,3365,NaN,NaN,NaN,0.742712,9999.0,...,No data,-9999.000000,-9999.000000,-9999.0,No data,-9999.000000,-9999.000000,-9999.0,No data,0.551020
4,111011-None-None,4,111011,-9999,-9999,NaN,NaN,NaN,13.430995,9999.0,...,No data,-9999.000000,-9999.000000,-9999.0,No data,-9999.000000,-9999.000000,-9999.0,No data,0.551020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68505,None-YEM.5_1-None,68506,-9999,YEM.5_1,-9999,YEM,Yemen,Al Hudaydah,0.887022,-9999.0,...,No data,-9999.000000,-9999.000000,-9999.0,No data,-9999.000000,-9999.000000,-9999.0,No data,0.326531
68506,None-ZAF.1_1-None,68507,-9999,ZAF.1_1,-9999,ZAF,South Africa,Eastern Cape,0.019523,-9999.0,...,No data,-9999.000000,-9999.000000,-9999.0,No data,-9999.000000,-9999.000000,-9999.0,No data,0.326531
68507,None-ZAF.4_1-None,68508,-9999,ZAF.4_1,-9999,ZAF,South Africa,KwaZulu-Natal,0.085616,-9999.0,...,No data,-9999.000000,-9999.000000,-9999.0,No data,-9999.000000,-9999.000000,-9999.0,No data,0.326531
68508,None-ZAF.9_1-2940,68509,-9999,ZAF.9_1,2940,ZAF,South Africa,Western Cape,0.015411,-9999.0,...,No data,-9999.000000,-9999.000000,-9999.0,No data,-9999.000000,-9999.000000,-9999.0,No data,0.326531
68509,None-ZAF.9_1-None,68510,-9999,ZAF.9_1,-9999,ZAF,South Africa,Western Cape,0.449872,-9999.0,...,No data,-9999.000000,-9999.000000,-9999.0,No data,-9999.000000,-9999.000000,-9999.0,No data,0.326531

## **Seleccion de variables de interes**

In [3]:
# clasificar columnas en categorias, y crear una lista de cada categoria con los nombres de las columnas correspondientes
identificadores = [
    "string_id", 
    "aq30_id",
    "name_0",
    "name_1",
    "area_km2"
]

riesgo_hidrologico = [
    "bws_score",   # Baseline water stress es el score de estrés hídrico de referencia
    "bwd_score",   # Water depletion es el score de agotamiento del agua
    "iav_score",   # Interannual variability es el score de variabilidad interanual
    "sev_score",   # Seasonal variability es el score de variabilidad estacional
    "drr_score"    # Drought risk es el score de riesgo de sequía
]

eventos_hidrologicos = [
    # "gtd_score",   # Groundwater table decline es el score de riesgo de declive de la tabla de agua subterránea, pero no se encuentra en el dataset
    "rfr_score",   # River flood risk es el score de riesgo de inundación fluvial
    "cfr_score"    # Coastal flood risk es el score de riesgo de inundación costera
]

calidad_agua = [
    "ucw_score",   # Untreated wastewater es el score de aguas residuales sin tratar
    "cep_score",   # Coastal eutrophication es el score de eutrofización costera
    "udw_score",   # No drinking water es el score de ausencia de agua potable
    "usa_score"    # No sanitation es el score de ausencia de saneamiento
]

por_industria = [
    "w_awr_agr_tot_score",   # Agriculture es el score de agricultura
    "w_awr_che_tot_score",   # Chemicals es el score de productos químicos
    "w_awr_con_tot_score",   # Construction materials es el score de materiales de construcción
    "w_awr_elp_tot_score",   # Electric power es el score de energía eléctrica
    "w_awr_fnb_tot_score",   # Food & beverage es el score de alimentos y bebidas
    "w_awr_min_tot_score",   # Mining es el score de minería
    "w_awr_ong_tot_score",   # Oil & gas es el score de petróleo y gas
    "w_awr_smc_tot_score",   # Semiconductor es el score de semiconductor
    "w_awr_tex_tot_score"    # Textile es el score de textil
]

In [4]:
df_selected = df[identificadores + riesgo_hidrologico + eventos_hidrologicos + calidad_agua + por_industria]
df_selected.head()

,string_id,aq30_id,name_0,name_1,area_km2,bws_score,bwd_score,iav_score,sev_score,drr_score,...,usa_score,w_awr_agr_tot_score,w_awr_che_tot_score,w_awr_con_tot_score,w_awr_elp_tot_score,w_awr_fnb_tot_score,w_awr_min_tot_score,w_awr_ong_tot_score,w_awr_smc_tot_score,w_awr_tex_tot_score
0,111011-EGY.11_1-3365,0,Egypt,Al Qahirah,4.223754,5.0,5.0,5.0,3.194805,-9999.0,...,0.890711,-9999.0,3.787802,4.162035,4.278249,4.318992,3.324107,2.095742,4.067326,3.705279
1,111011-EGY.15_1-3365,1,Egypt,As Suways,1846.012343,5.0,5.0,5.0,3.194805,-9999.0,...,0.890711,-9999.0,3.787802,4.162035,4.278249,4.318992,3.324107,2.095742,4.067326,3.705279
2,111011-EGY.15_1-None,2,Egypt,As Suways,30.526067,5.0,5.0,5.0,3.194805,-9999.0,...,0.890711,-9999.0,3.787802,4.162035,4.278249,4.318992,3.324107,2.095742,4.067326,3.705279
3,111011-None-3365,3,NaN,NaN,0.742712,5.0,5.0,5.0,3.194805,-9999.0,...,0.890711,-9999.0,-9999.000000,-9999.000000,4.288761,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000
4,111011-None-None,4,NaN,NaN,13.430995,5.0,5.0,5.0,3.194805,-9999.0,...,0.890711,-9999.0,-9999.000000,-9999.000000,4.288761,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000

## **Gestionar valores nulls e inconsistentes**

In [5]:
# contar valores nulos por columna
df_selected.isna().sum().sort_values(ascending=False)

name_0                 10022
name_1                 10022
string_id                  0
udw_score                  0
w_awr_smc_tot_score        0
w_awr_ong_tot_score        0
w_awr_min_tot_score        0
w_awr_fnb_tot_score        0
w_awr_elp_tot_score        0
w_awr_con_tot_score        0
w_awr_che_tot_score        0
w_awr_agr_tot_score        0
usa_score                  0
ucw_score                  0
cep_score                  0
aq30_id                    0
cfr_score                  0
rfr_score                  0
drr_score                  0
sev_score                  0
iav_score                  0
bwd_score                  0
bws_score                  0
area_km2                   0
w_awr_tex_tot_score        0
dtype: int64

In [6]:
df_selected = df_selected[~(df_selected['name_0'].isna() | df_selected['name_1'].isna())]

In [7]:
df_selected.isnull().sum().sort_values(ascending=False)

string_id              0
cep_score              0
w_awr_smc_tot_score    0
w_awr_ong_tot_score    0
w_awr_min_tot_score    0
w_awr_fnb_tot_score    0
w_awr_elp_tot_score    0
w_awr_con_tot_score    0
w_awr_che_tot_score    0
w_awr_agr_tot_score    0
usa_score              0
udw_score              0
ucw_score              0
aq30_id                0
cfr_score              0
rfr_score              0
drr_score              0
sev_score              0
iav_score              0
bwd_score              0
bws_score              0
area_km2               0
name_1                 0
name_0                 0
w_awr_tex_tot_score    0
dtype: int64

## **Eliminacion de valores inconsistentes**

In [8]:
# contar los valores -9999 por cada columna, y mostrar el porcentaje respecto al total de filas, crear un nuevo dataframe con el resultado, y mostrarlo
missing_values_count = df_selected.isin([-9999]).sum()
total_rows = len(df_selected)
missing_values_percentage = (missing_values_count / total_rows) * 100
df_missing_values = pd.DataFrame({'Missing Values': missing_values_count, 'Percentage': missing_values_percentage})
df_missing_values[df_missing_values['Percentage'] > 0].sort_values(by='Percentage', ascending=False)

                     Missing Values  Percentage
drr_score                     10993   18.795308
w_awr_agr_tot_score            9719   16.617084
w_awr_fnb_tot_score            4964    8.487211
w_awr_smc_tot_score            4611    7.883668
w_awr_elp_tot_score            4589    7.846054
iav_score                      4537    7.757147
sev_score                      4537    7.757147
w_awr_con_tot_score            4440    7.591301
w_awr_tex_tot_score            4403    7.528040
w_awr_che_tot_score            4030    6.890302
bws_score                      3919    6.700520
bwd_score                      3919    6.700520
w_awr_min_tot_score            3905    6.676583
cep_score                      3464    5.922582
w_awr_ong_tot_score            2753    4.706948
udw_score                      2596    4.438517
cfr_score                      2596    4.438517
rfr_score                      2596    4.438517
usa_score                      2596    4.438517
ucw_score                       787    1.345575

In [9]:
df_cleaned = df_selected[df_selected['drr_score'] != -9999]
df_cleaned

,string_id,aq30_id,name_0,name_1,area_km2,bws_score,bwd_score,iav_score,sev_score,drr_score,...,usa_score,w_awr_agr_tot_score,w_awr_che_tot_score,w_awr_con_tot_score,w_awr_elp_tot_score,w_awr_fnb_tot_score,w_awr_min_tot_score,w_awr_ong_tot_score,w_awr_smc_tot_score,w_awr_tex_tot_score
89,111081-ERI.2_1-3365,89,Eritrea,Debub,6.445810,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.505411,4.396533,4.556903,4.254894,4.660862,4.421376,4.432915,4.644985,4.625870
90,111081-ERI.6_1-3365,90,Eritrea,Semenawi Keyih Bahri,210.189947,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.505411,4.396533,4.556903,4.254894,4.660862,4.421376,4.432915,4.644985,4.625870
92,111081-SDN.11_1-1775,92,Sudan,Red Sea,725.925119,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.341763,4.286233,4.365973,4.230958,4.410905,4.309340,4.314742,4.483448,4.459413
93,111081-SDN.11_1-1930,93,Sudan,Red Sea,345.262750,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.501896,4.366672,4.541816,4.250959,4.625538,4.374278,4.363119,4.606872,4.561502
94,111081-SDN.11_1-3365,94,Sudan,Red Sea,2989.133981,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.501896,4.366672,4.541816,4.250959,4.625538,4.374278,4.363119,4.606872,4.561502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61195,832808-CAN.3_1-352,61194,Canada,Manitoba,1657.645142,0.000000,0.001827,5.000000,2.576914,1.512279,...,0.0,1.006019,0.549238,0.598137,0.795594,0.754779,0.523294,0.309699,0.879260,0.637502
61196,832808-CAN.8_1-352,61195,Canada,Nunavut,1468.762076,0.000000,0.001827,5.000000,2.576914,1.512279,...,0.0,1.006019,0.549238,0.598137,0.795594,0.754779,0.523294,0.309699,0.879260,0.637502
61197,832809-CAN.12_1-352,61196,Canada,Saskatchewan,174.810225,0.000000,0.000025,3.387390,0.902210,1.473108,...,0.0,0.840139,0.411614,0.458744,0.574676,0.631738,0.412238,0.230250,0.705099,0.527545
61198,832809-CAN.3_1-352,61197,Canada,Manitoba,7985.673792,0.000000,0.000025,3.387390,0.902210,1.473108,...,0.0,0.840139,0.411614,0.458744,0.574676,0.631738,0.412238,0.230250,0.705099,0.527545
61199,832809-CAN.8_1-352,61198,Canada,Nunavut,191.681814,0.000000,0.000025,3.387390,0.902210,1.473108,...,0.0,0.840139,0.411614,0.458744,0.574676,0.631738,0.412238,0.230250,0.705099,0.527545

In [10]:
# contar los valores -9999 por cada columna, y mostrar el porcentaje respecto al total de filas, crear un nuevo dataframe con el resultado, y mostrarlo
missing_values_count = df_cleaned.isin([-9999]).sum()
total_rows = len(df_cleaned)
missing_values_percentage = (missing_values_count / total_rows) * 100
df_missing_values = pd.DataFrame({'Missing Values': missing_values_count, 'Percentage': missing_values_percentage})
df_missing_values[df_missing_values['Percentage'] > 0].sort_values(by='Percentage', ascending=False)

                     Missing Values  Percentage
w_awr_smc_tot_score             726    1.528582
w_awr_fnb_tot_score             547    1.151700
w_awr_tex_tot_score             518    1.090641
ucw_score                       497    1.046426
w_awr_agr_tot_score             363    0.764291
iav_score                       242    0.509527
sev_score                       242    0.509527
bws_score                       232    0.488472
bwd_score                       232    0.488472
w_awr_con_tot_score             232    0.488472
w_awr_elp_tot_score             232    0.488472
w_awr_che_tot_score             192    0.404253
cep_score                       151    0.317928
w_awr_min_tot_score              21    0.044215
w_awr_ong_tot_score               3    0.006316

In [11]:
df_cleaned = df_cleaned[df_cleaned['w_awr_smc_tot_score'] != -9999]
# contar los valores -9999 por cada columna, y mostrar el porcentaje respecto al total de filas, crear un nuevo dataframe con el resultado, y mostrarlo
missing_values_count = df_cleaned.isin([-9999]).sum()
total_rows = len(df_cleaned)
missing_values_percentage = (missing_values_count / total_rows) * 100
df_missing_values = pd.DataFrame({'Missing Values': missing_values_count, 'Percentage': missing_values_percentage})
df_missing_values[df_missing_values['Percentage'] > 0].sort_values(by='Percentage', ascending=False)

                     Missing Values  Percentage
cep_score                       129    0.275824
w_awr_agr_tot_score             129    0.275824
iav_score                        10    0.021382
sev_score                        10    0.021382

In [12]:
df_cleaned = df_cleaned[df_cleaned['cep_score'] != -9999]
# contar los valores -9999 por cada columna, y mostrar el porcentaje respecto al total de filas, crear un nuevo dataframe con el resultado, y mostrarlo
missing_values_count = df_cleaned.isin([-9999]).sum()
total_rows = len(df_cleaned)
missing_values_percentage = (missing_values_count / total_rows) * 100
df_missing_values = pd.DataFrame({'Missing Values': missing_values_count, 'Percentage': missing_values_percentage})
df_missing_values[df_missing_values['Percentage'] > 0].sort_values(by='Percentage', ascending=False)

           Missing Values  Percentage
iav_score              10    0.021441
sev_score              10    0.021441

In [13]:
df_cleaned = df_cleaned[df_cleaned['iav_score'] != -9999]
# contar los valores -9999 por cada columna, y mostrar el porcentaje respecto al total de filas, crear un nuevo dataframe con el resultado, y mostrarlo
missing_values_count = df_cleaned.isin([-9999]).sum()
total_rows = len(df_cleaned)
missing_values_percentage = (missing_values_count / total_rows) * 100
df_missing_values = pd.DataFrame({'Missing Values': missing_values_count, 'Percentage': missing_values_percentage})
df_missing_values[df_missing_values['Percentage'] > 0].sort_values(by='Percentage', ascending=False)

Empty DataFrame
Columns: [Missing Values, Percentage]
Index: []

In [14]:
df_cleaned

,string_id,aq30_id,name_0,name_1,area_km2,bws_score,bwd_score,iav_score,sev_score,drr_score,...,usa_score,w_awr_agr_tot_score,w_awr_che_tot_score,w_awr_con_tot_score,w_awr_elp_tot_score,w_awr_fnb_tot_score,w_awr_min_tot_score,w_awr_ong_tot_score,w_awr_smc_tot_score,w_awr_tex_tot_score
89,111081-ERI.2_1-3365,89,Eritrea,Debub,6.445810,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.505411,4.396533,4.556903,4.254894,4.660862,4.421376,4.432915,4.644985,4.625870
90,111081-ERI.6_1-3365,90,Eritrea,Semenawi Keyih Bahri,210.189947,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.505411,4.396533,4.556903,4.254894,4.660862,4.421376,4.432915,4.644985,4.625870
92,111081-SDN.11_1-1775,92,Sudan,Red Sea,725.925119,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.341763,4.286233,4.365973,4.230958,4.410905,4.309340,4.314742,4.483448,4.459413
93,111081-SDN.11_1-1930,93,Sudan,Red Sea,345.262750,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.501896,4.366672,4.541816,4.250959,4.625538,4.374278,4.363119,4.606872,4.561502
94,111081-SDN.11_1-3365,94,Sudan,Red Sea,2989.133981,4.745978,4.708000,3.841307,3.944071,2.215140,...,5.0,4.501896,4.366672,4.541816,4.250959,4.625538,4.374278,4.363119,4.606872,4.561502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61195,832808-CAN.3_1-352,61194,Canada,Manitoba,1657.645142,0.000000,0.001827,5.000000,2.576914,1.512279,...,0.0,1.006019,0.549238,0.598137,0.795594,0.754779,0.523294,0.309699,0.879260,0.637502
61196,832808-CAN.8_1-352,61195,Canada,Nunavut,1468.762076,0.000000,0.001827,5.000000,2.576914,1.512279,...,0.0,1.006019,0.549238,0.598137,0.795594,0.754779,0.523294,0.309699,0.879260,0.637502
61197,832809-CAN.12_1-352,61196,Canada,Saskatchewan,174.810225,0.000000,0.000025,3.387390,0.902210,1.473108,...,0.0,0.840139,0.411614,0.458744,0.574676,0.631738,0.412238,0.230250,0.705099,0.527545
61198,832809-CAN.3_1-352,61197,Canada,Manitoba,7985.673792,0.000000,0.000025,3.387390,0.902210,1.473108,...,0.0,0.840139,0.411614,0.458744,0.574676,0.631738,0.412238,0.230250,0.705099,0.527545
61199,832809-CAN.8_1-352,61198,Canada,Nunavut,191.681814,0.000000,0.000025,3.387390,0.902210,1.473108,...,0.0,0.840139,0.411614,0.458744,0.574676,0.631738,0.412238,0.230250,0.705099,0.527545

## **Data augmentation**

> clasificar los paises por regiones

In [15]:
africa = [
    'Egypt','Sudan','Eritrea','Somalia','Ethiopia','Djibouti',
    'Kenya','Tanzania','Uganda','South Sudan','Zambia','Mozambique',
    'Malawi','Zimbabwe','Democratic Republic of the Congo','Botswana',
    'Namibia','Angola','South Africa','Swaziland','Lesotho',
    'Republic of Congo','Gabon','Central African Republic','Cameroon',
    'Burundi','Rwanda','Equatorial Guinea','Nigeria',
    'São Tomé and Príncipe','Chad','Benin','Niger','Mali',
    'Algeria','Burkina Faso','Mauritania',"Côte d'Ivoire",
    'Guinea','Sierra Leone','Togo','Ghana','Liberia','Guinea-Bissau',
    'Senegal','Gambia','Western Sahara','Morocco','Tunisia','Libya',
    'Madagascar','Comoros','Seychelles','Cape Verde','Mauritius',
    'Reunion','Mayotte','Saint Helena','French Southern Territories'
]

europe = [
    'Spain','Portugal','Italy','Greece','Bulgaria','Macedonia',
    'Serbia','Kosovo','Albania','Montenegro',
    'Bosnia and Herzegovina','Croatia','Slovenia','Austria',
    'Switzerland','France','San Marino','Andorra','Malta',
    'Germany','Belgium','Netherlands','Luxembourg','Liechtenstein',
    'United Kingdom','Ireland','Denmark','Lithuania','Latvia',
    'Estonia','Finland','Norway','Sweden','Iceland','Poland',
    'Romania','Hungary','Slovakia','Czech Republic','Ukraine',
    'Belarus','Moldova','Russia','Georgia',
    'Guernsey','Jersey','Isle of Man','Faroe Islands','Åland',
    'Svalbard and Jan Mayen'
]

asia = [
    'Yemen','Israel','Palestina','Lebanon','Syria','Turkey','Cyprus',
    'Iran','Afghanistan','Iraq','Azerbaijan','Armenia','Pakistan',
    'Saudi Arabia','Jordan','Kuwait','Bahrain','Qatar',
    'United Arab Emirates','Oman','China','Mongolia','Japan',
    'North Korea','South Korea','Taiwan','Hong Kong','Macao',
    'Vietnam','Laos','Cambodia','Thailand','Myanmar','Malaysia',
    'Singapore','India','Bangladesh','Nepal','Bhutan','Sri Lanka',
    'Tajikistan','Kyrgyzstan','Indonesia','Timor-Leste','Brunei',
    'Philippines','Kazakhstan','Uzbekistan','Turkmenistan',
    'Akrotiri and Dhekelia','Northern Cyprus'
]

north_america = [
    'United States','Canada','Mexico','Greenland',
    'Bermuda','Saint Pierre and Miquelon'
]

central_america = [
    'Guatemala','Belize','Honduras','Nicaragua',
    'Costa Rica','Panama','El Salvador'
]

caribbean = [
    'Bahamas','Cuba','Jamaica','Haiti','Dominican Republic',
    'Barbados','Trinidad and Tobago','Puerto Rico',
    'Bonaire, Sint Eustatius and Saba','Grenada','Saint Lucia',
    'Martinique','Saint Vincent and the Grenadines',
    'Turks and Caicos Islands','Cayman Islands',
    'Antigua and Barbuda','Dominica','Guadeloupe',
    'Saint Kitts and Nevis','Montserrat',
    'British Virgin Islands','Virgin Islands, U.S.'
]

south_america = [
    'Colombia','Venezuela','Brazil','Guyana','Suriname',
    'French Guiana','Bolivia','Peru','Ecuador','Uruguay',
    'Argentina','Paraguay','Chile'
]

oceania = [
    'Australia','New Zealand','Papua New Guinea','Fiji',
    'Solomon Islands','Vanuatu','Samoa','Tonga','Tuvalu',
    'Micronesia','Palau','Nauru','New Caledonia',
    'French Polynesia','Wallis and Futuna','Tokelau',
    'Guam','Northern Mariana Islands',
    'United States Minor Outlying Islands','American Samoa'
]
continent_map = {}

for c in africa:
    continent_map[c] = 'Africa'

for c in europe:
    continent_map[c] = 'Europe'

for c in asia:
    continent_map[c] = 'Asia'

for c in north_america:
    continent_map[c] = 'North America'
for c in central_america:
    continent_map[c] = 'Central America'
for c in caribbean:
    continent_map[c] = 'Caribbean'
for c in south_america:
    continent_map[c] = 'South America'

for c in oceania:
    continent_map[c] = 'Oceania'

df_cleaned['continent'] = df_cleaned['name_0'].map(continent_map)
df_cleaned.groupby('continent')['name_0'].count()

continent
Africa              9784
Asia               12379
Caribbean            330
Central America      736
Europe              8925
North America       6008
Oceania             2152
South America       6316
Name: name_0, dtype: int64

In [16]:
df_cleaned[df_cleaned['continent'].isna()]['name_0'].unique()

array([], dtype=object)

## **Data Transformation: Restructuring**

> Pasar de wide format a long format para facilitar la visualizacion de las variables

In [17]:
# Diccionario score -> categoria
mapa_categorias = {}

for col in riesgo_hidrologico:
    mapa_categorias[col] = "riesgo_hidrologico"

for col in eventos_hidrologicos:
    mapa_categorias[col] = "eventos_hidrologicos"

for col in calidad_agua:
    mapa_categorias[col] = "calidad_agua"

for col in por_industria:
    mapa_categorias[col] = "por_industria"

# Todas las columnas score
score_cols = list(mapa_categorias.keys())

# Supongamos que tu dataframe original se llama df_cleaned
# Aquí se conservan las demás columnas que NO son scores
id_cols = [col for col in df_cleaned.columns if col not in score_cols]

# Pasar a formato largo
df_long = df_cleaned.melt(
    id_vars=id_cols,
    value_vars=score_cols,
    var_name="score",
    value_name="value"
)

# Agregar la categoría
df_long["category"] = df_long["score"].map(mapa_categorias)

df_long

,string_id,aq30_id,name_0,name_1,area_km2,continent,score,value,category
0,111081-ERI.2_1-3365,89,Eritrea,Debub,6.445810,Africa,bws_score,4.745978,riesgo_hidrologico
1,111081-ERI.6_1-3365,90,Eritrea,Semenawi Keyih Bahri,210.189947,Africa,bws_score,4.745978,riesgo_hidrologico
2,111081-SDN.11_1-1775,92,Sudan,Red Sea,725.925119,Africa,bws_score,4.745978,riesgo_hidrologico
3,111081-SDN.11_1-1930,93,Sudan,Red Sea,345.262750,Africa,bws_score,4.745978,riesgo_hidrologico
4,111081-SDN.11_1-3365,94,Sudan,Red Sea,2989.133981,Africa,bws_score,4.745978,riesgo_hidrologico
...,...,...,...,...,...,...,...,...,...
932595,832808-CAN.3_1-352,61194,Canada,Manitoba,1657.645142,North America,w_awr_tex_tot_score,0.637502,por_industria
932596,832808-CAN.8_1-352,61195,Canada,Nunavut,1468.762076,North America,w_awr_tex_tot_score,0.637502,por_industria
932597,832809-CAN.12_1-352,61196,Canada,Saskatchewan,174.810225,North America,w_awr_tex_tot_score,0.527545,por_industria
932598,832809-CAN.3_1-352,61197,Canada,Manitoba,7985.673792,North America,w_awr_tex_tot_score,0.527545,por_industria
932599,832809-CAN.8_1-352,61198,Canada,Nunavut,191.681814,North America,w_awr_tex_tot_score,0.527545,por_industria

In [18]:
mapa_nombres = {
    "bws_score": "Baseline water stress",
    "bwd_score": "Water depletion",
    "iav_score": "Interannual variability",
    "sev_score": "Seasonal variability",
    "drr_score": "Drought risk",
    "rfr_score": "River flood risk",
    "cfr_score": "Coastal flood risk",
    "ucw_score": "Untreated wastewater",
    "cep_score": "Coastal eutrophication",
    "udw_score": "No drinking water",
    "usa_score": "No sanitation",
    "w_awr_agr_tot_score": "Agriculture",
    "w_awr_che_tot_score": "Chemicals",
    "w_awr_con_tot_score": "Construction materials",
    "w_awr_elp_tot_score": "Electric power",
    "w_awr_fnb_tot_score": "Food & beverage",
    "w_awr_min_tot_score": "Mining",
    "w_awr_ong_tot_score": "Oil & gas",
    "w_awr_smc_tot_score": "Semiconductor",
    "w_awr_tex_tot_score": "Textile"
}

df_long["score_nombre"] = df_long["score"].map(mapa_nombres)
df_long

,string_id,aq30_id,name_0,name_1,area_km2,continent,score,value,category,score_nombre
0,111081-ERI.2_1-3365,89,Eritrea,Debub,6.445810,Africa,bws_score,4.745978,riesgo_hidrologico,Baseline water stress
1,111081-ERI.6_1-3365,90,Eritrea,Semenawi Keyih Bahri,210.189947,Africa,bws_score,4.745978,riesgo_hidrologico,Baseline water stress
2,111081-SDN.11_1-1775,92,Sudan,Red Sea,725.925119,Africa,bws_score,4.745978,riesgo_hidrologico,Baseline water stress
3,111081-SDN.11_1-1930,93,Sudan,Red Sea,345.262750,Africa,bws_score,4.745978,riesgo_hidrologico,Baseline water stress
4,111081-SDN.11_1-3365,94,Sudan,Red Sea,2989.133981,Africa,bws_score,4.745978,riesgo_hidrologico,Baseline water stress
...,...,...,...,...,...,...,...,...,...,...
932595,832808-CAN.3_1-352,61194,Canada,Manitoba,1657.645142,North America,w_awr_tex_tot_score,0.637502,por_industria,Textile
932596,832808-CAN.8_1-352,61195,Canada,Nunavut,1468.762076,North America,w_awr_tex_tot_score,0.637502,por_industria,Textile
932597,832809-CAN.12_1-352,61196,Canada,Saskatchewan,174.810225,North America,w_awr_tex_tot_score,0.527545,por_industria,Textile
932598,832809-CAN.3_1-352,61197,Canada,Manitoba,7985.673792,North America,w_awr_tex_tot_score,0.527545,por_industria,Textile
932599,832809-CAN.8_1-352,61198,Canada,Nunavut,191.681814,North America,w_awr_tex_tot_score,0.527545,por_industria,Textile

## **Data Saving**

>El dataset limpio se guarda para ser utilizado en la etapa de visualización

In [20]:
import os
os.makedirs("data", exist_ok=True)
df_long.to_csv("data/cleaned_data_long_format.csv", index=False)
# si se guardo el archivo, mostrar un mensaje de confirmacion
if os.path.exists("data/cleaned_data_long_format.csv"):
    print("Archivo guardado exitosamente en data/cleaned_data_long_format.csv")

Archivo guardado exitosamente en data/cleaned_data_long_format.csv